Update mark-github-24 sizing
primer/octicons pull request #1050
Opened 2024-12-11 20:06 UTC by durfee

This PR fixes a sizing issue of the GitHub mark (see below)

<img width="102" alt="Screenshot 2024-11-28 at 10 04 38" src="https://github.com/user-attachments/assets/9000e3f7-882b-4ec7-9f9c-8fef94e12ec5" />

Here's a before/after 

![image](https://github.com/user-attachments/assets/5604b460-4e72-4a67-9fd8-f02e756c5e2b)

Old is in purple, new is in grey.

2024-12-11 20:07 UTC, durfee commented
Following up with the branch feedback in [Figma](https://www.figma.com/design/1ljgTFkT5NKNRfq5hw07JQ/branch/jGQIGJrmwTzwB9Cy66TFTp/Octicons?t=gph5eg8oemcEVuN0-11)

2024-12-16 19:57 UTC, camertron commented
Wait sorry, why is the markdown icon being deleted?

2024-12-16 19:58 UTC, camertron requested changes
Wait sorry, why is the markdown icon being deleted?

2024-12-16 20:21 UTC, durfee commented
Oh goodness my bad, I copy pasted over the wrong one 🙈 Uploading the correct change in a moment

2024-12-16 21:32 UTC, camertron approved these changes
Thank you!

2025-02-18 19:58 UTC, CameronFoxly approved these changes
LGTM!

2025-02-18 20:43 UTC, merged