Save file-directory-32.svg, file-directory-fill-32.svg
primer/octicons pull request #736
Opened 2022-02-02 15:03 UTC by edokoa

Updated file-directory icons to fix naming problem and add non-filled icon.

2022-02-02 15:28 UTC, colebemis commented on .changeset/slimy-peaches-draw.md
> +"@primer/octicons": patch
Breaking changes require `major` version bumps:
```suggestion
"@primer/octicons": major
```

2022-02-02 15:36 UTC, ashygee requested changes
It looks like you're uploading the 2x version of the 16px icon because they're appended with `-32`

2022-02-03 08:06 UTC, edokoa commented
@ashygee my bad. It's a classic. I fixed it.

2022-02-03 16:15 UTC, colebemis commented on .changeset/slimy-peaches-draw.md
> +This patch fixes two problems:
```suggestion
---

This patch fixes two problems:
```

2022-02-03 16:16 UTC, colebemis approved these changes
🚢

2022-02-04 14:30 UTC, ashygee approved these changes
🚀

2022-02-15 17:52 UTC, merged